FROM rust:bookworm AS builder

WORKDIR /app
COPY . .
RUN cargo build --release -p backend

FROM debian:bookworm-slim

WORKDIR /app
COPY --from=builder /app/target/release/backend /usr/local/bin/backend

EXPOSE 3000

CMD ["backend"]
